# theme: jekyll-theme-slate
remote_theme: pmarsceill/just-the-docs
title: Volumetric Capture
description: A low-cost, flexible and scalable multi RGB-D sensor acquisition system
show_downloads: false
baseurl: "/VolumetricCapture" # the subpath of your site, e.g. /blog
url: "https://vcl3d.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# url: "https://github.com/VCL3D"

permalink: pretty
exclude: ["README.md", "/assets/usage/diagrams.md", "RELEASE_NOTES.md"]

logo: /assets/images/icons/logo.png

search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 3
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

  # Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "Volumetric Capture on GitHub":
    - "//github.com/VCL3D/VolumetricCapture/"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_sensitive # Capital letters sorted before lowercase

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Created by the <a href=\"https://github.com/VCL3D\">3D vision team</a> of the <a href=\"https://vcl.iti.gr\">Visual Computing Lab</a>"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: nil

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
ga_tracking: UA-147231916-1
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   envs: all
